global:
  scrape_interval: 5s  # How often to scrape metrics

scrape_configs:
  - job_name: 'wallet-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['wallet-service-container:8080']   # Use container/service name from Compose

rule_files:
  - "/etc/prometheus/alert-rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"   # Use service name from Compose
